endpoints:
    - task: question_answering
      model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned95_obs_quant-none
      route: /invocations
      batch_size: 1
      kwargs:
        sequence_length: 128