endpoints:
    - task: question_answering
      route: /invocations
      model: zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/pruned95_obs_quant-none
      batch_size: 1
      bucketing:
        sequence_lengths: [128]